konveyor/move2kube-website

docs/installation/web-interface.md

chore: update warning since CNB is no longer supported

---

.github/workflows/releaseinfo.yml

ci: use the personal access token for requests to other repos

---

docs/tutorials/cli-local-workflow.md
docs/tutorials/transformer-workflow.md

feat: custom transformer tutorial

---

_includes/head.html
_includes/head_custom.html

fix: add css to prevent long lines of code from overflowing the container

---

docs/tutorials/cli-workflow.md
docs/tutorials/ui-workflow.md

fix: clarify instructions for the QA and deploy command

---

docs/tutorials/migration-workflow/collect.md
docs/tutorials/migration-workflow/custom-transformer-1.md
docs/tutorials/migration-workflow/custom-transformer-2.md
docs/tutorials/migration-workflow/custom-transformer-3.md
docs/tutorials/migration-workflow/custom-transformer-4.md
docs/tutorials/migration-workflow/migration-workflow.md
docs/tutorials/migration-workflow/plan.md
docs/tutorials/migration-workflow/transform.md

feat: add a tutorial to show the user story and migration workflow

---

docs/documentation/path-mapping.md
docs/installation/web-interface.md
docs/tutorials/migration-workflow/collect.md
docs/tutorials/migration-workflow/migration-workflow.md
docs/tutorials/migration-workflow/plan.md
docs/tutorials/transformer-workflow.md

chore: cleanup some mentions of vendor specific stuff

docs: add more instructions for migration workflow

---

docs/tutorials/migration-workflow/ingress-annotator.md

doc: Added custom ingress annotator tutorial

---

docs/tutorials/migration-workflow/parameterizer.md

fix: fixed link

---

docs/tutorials/migration-workflow/folder-customizer.md
docs/tutorials/migration-workflow/parameterizer.md
docs/tutorials/migration-workflow/script-inject.md

fix: Format issues in the snippets

---

docs/tutorials/migration-workflow/parameterizer.md
docs/tutorials/migration-workflow/transform.md

fix: hyperlink order of the migration-workflow

---

.github/workflows/releaseinfo.yml

chore: move helm chart into the ui repo

---

docs/tutorials/cli-workflow.md
docs/tutorials/migration-workflow/migration-workflow.md
docs/tutorials/running-non-interactively.md
docs/tutorials/running-the-same-workflow-twice.md
docs/tutorials/transformer-workflow.md
docs/tutorials/ui-workflow.md

docs: tutorial on how to use the config file to answer the questions

---

docs/tutorials/customizing-the-output/customizing-the-output.md

fix: typo in the link to the transformer concept

---

docs/tutorials/cloud-foundry.md

fix: Update the plan file in the cloud-foundry tutorial

---

docs/tutorials/cloud-foundry.md

fix: Correct typo and minor changes in cloud-foundry tutorial

---

docs/tutorials/cloud-foundry.md

fix: Emphasize the requirement of CF source code in CF tutorial

---

docs/installation/command-line-tool.md
docs/tutorials/migration-workflow/collect.md
docs/tutorials/migration-workflow/migration-workflow.md
docs/tutorials/migration-workflow/plan.md
docs/tutorials/migration-workflow/transform.md

fix: small updates to migration-workflow

---

scripts/download.sh

feat: Add download script

---

docs/installation/web-interface.md

chore: update stable version in installation instructions

---

docs/tutorials/customizing-the-output/ingress-annotator.md
docs/tutorials/migration-workflow/plan.md
scripts/download.sh

docs: updates to ingress annotator

---

scripts/download.sh

feat: Add support for specifying output directory

---

docs/tutorials/cli-workflow.md

fix: Corrected CLI install url

---

docs/tutorials/customizing-the-output/custom-parameterization-of-helm-charts-kustomize-octemplates.md

fix: Added raw block to yaml in parameterizer tutorial

---

docs/tutorials/customizing-the-output/add-custom-files-directories-in-custom-locations.md

fix: Corrected console text and fixed broken link

---

docs/documentation/presentation.md

fix: Update the pdf object size to make it clearly visible

---

docs/documentation/customization/customization.md
docs/documentation/customization/external/executable.md
docs/documentation/customization/external/external.md
docs/documentation/customization/external/starlark.md
docs/documentation/customization/purpose-built/parameterizer.md
docs/documentation/customization/purpose-built/purpose-built.md
docs/documentation/customization/special/router.md
docs/documentation/customization/special/special.md

fix: fix customization

---

docs/tutorials/customizing-the-output/add-custom-files-directories-in-custom-locations.md
docs/tutorials/customizing-the-output/custom-annotations.md
docs/tutorials/customizing-the-output/custom-dockerfile-change-inbuilt-behavior.md
docs/tutorials/customizing-the-output/custom-parameterization-of-helm-charts-kustomize-octemplates.md
docs/tutorials/migration-workflow/plan.md
docs/tutorials/migration-workflow/transform.md

chore: rename customers-tomcat app

---

docs/tutorials/customizing-the-output/customizing-the-output.md
docs/tutorials/dotnetcore.md
docs/tutorials/kubernetes.md
docs/tutorials/migration-workflow/migration-workflow.md

chore: reorder tutorials

---

docs/concepts/transformer.md
docs/tutorials/cli-workflow.md
docs/tutorials/customizing-the-output/custom-dockerfile-change-built-in-behavior.md
docs/tutorials/kubernetes.md
docs/tutorials/migration-workflow/collect.md
docs/tutorials/ui-workflow.md

fix: fix broken links

---

docs/transformers/external/executable.md
docs/transformers/external/external.md
docs/transformers/external/starlark.md
docs/transformers/purpose-built/parameterizer.md
docs/transformers/purpose-built/purpose-built.md
docs/transformers/special/router.md
docs/transformers/special/special.md
docs/transformers/transformers.md
docs/tutorials/kubernetes.md

docs: rename customization as transformers

---

docs/presentation.md

fix: fix nav order of presentation

---

docs/tutorials/customizing-the-output/add-custom-files-directories-in-custom-locations.md

fix: fix broken link

---

scripts/rebase-before-release.sh

chore: add a script to help rebase before making a release

---

docs/tutorials/migration-workflow/collect.md

fix: Update the m2k_collect output

---

scripts/download.sh

feat: add quiet option to download script

---

_includes/nav.html
docs/tutorials/customizing-the-output/customizing-the-output.md

fix: fix nav_order sort

---

docs/tutorials/kubernetes.md

docs: update paramterize yamls tutorial

---

scripts/download.sh

fix: download script to check for dependencies and give a warning

---

scripts/download.sh

fix: typo in previous fix PR

---

scripts/download.sh

fix: fix typo in download script

---

docs/tutorials/kubernetes.md

fix: Update the Parameterizing Kubernetes YAMLs tutorial

---

docs/tutorials/migration-workflow/plan.md

fix: Updated version

---

docs/tutorials/custom-cluster-selector.md
docs/tutorials/customizing-the-output/customizing-the-output.md
docs/tutorials/migration-workflow/migration-workflow.md

feat: Add custom cluster selector tutorial

---

.github/workflows/releaseinfo.yml

feat: trigger formula creation in homebrew repo

---

docs/tutorials/migration-workflow/plan.md
docs/tutorials/migration-workflow/transform.md

chore: update plan output in tutorial and add link to m2kconfig file

---

docs/tutorials/migration-workflow/plan.md
docs/tutorials/migration-workflow/transform.md

chore: update tutorials with latest output

---

docs/tutorials/migration-workflow/transform.md

chore: update the qa for the enterprise tutorial

---

docs/installation/command-line-tool.md

docs: document some features of the install script and add simpler install commands

---

docs/tutorials/cloud-foundry.md

fix: Update the tutorial instructions related to CF deployment

---

docs/tutorials/cloud-foundry.md

Signed-off-by: Souradeep Dutta <sourae.47@gmail.com>

Update cloud-foundry.md - making minor changes to doc

---

docs/transformers/external/starlark.md

Signed-off-by: Mehant Kammakomati <kmehant@gmail.com>

feat: add starlark documentation

---

docs/transformers/external/starlark.md

Signed-off-by: Mehant Kammakomati <kmehant@gmail.com>

fix: add docs for find_xml_path

---

docs/transformers/purpose-built/parameterizer.md
package.json

chore: document how a parameterizer can keep the original value in the yaml it is parameterizing

---

docs/tutorials/customizing-the-output/custom-annotations.md

chore: update starlark tutorial since function names changed to have an underscore in the name

---

docs/transformers/external/starlark.md
docs/tutorials/customizing-the-output/custom-dockerfile-change-built-in-behavior.md

Updated the tutorial based on the workshop

feat: Update move2kube customize output tutorial for dockerfile and k8s location

---

.dockerignore
Dockerfile
Dockerfile.base
README.md
package.json

feat: add Dockerfiles for development purposes

---

docs/tutorials/cli-workflow.md
docs/tutorials/docker-compose.md
docs/tutorials/migration-workflow/transform.md

This fix is a part of an umbrella issue https://github.com/kubernetes/k8s.io/issues/4780

fix: migrate from k8s.gcr.io to registry.k8s.io

---

docs/transformers/external/executable.md
docs/tutorials/customizing-the-output/external-transformer-illustration.md

docs: External transformer sample tutorial

---

docs/transformers/external/starlark.md

Docs for https://github.com/konveyor/move2kube/pull/1050

docs: document the eval_template function that was added to Starlark transformer

---

docs/tutorials/collect-specific-cf-apps-metadata.md
docs/tutorials/custom-cluster-selector.md
docs/tutorials/customizing-the-output/customizing-the-output.md
docs/tutorials/docker-compose.md
docs/tutorials/dotnet.md
docs/tutorials/dotnetcore.md
docs/tutorials/kubernetes.md
docs/tutorials/migration-workflow/migration-workflow.md
docs/tutorials/move2kube-collect.md

feat: Add a complete tutorial on move2kube collect

---

docs/tutorials/cli-categories.md
docs/tutorials/cloud-foundry.md
docs/tutorials/collect-specific-cf-apps-metadata.md
docs/tutorials/custom-cluster-selector.md
docs/tutorials/customizing-the-output/customizing-the-output.md
docs/tutorials/docker-compose.md
docs/tutorials/dotnet.md
docs/tutorials/dotnetcore.md
docs/tutorials/kubernetes.md
docs/tutorials/migration-workflow/migration-workflow.md
docs/tutorials/move2kube-collect.md

fix: Update the ordering of the tutorials
